version: '3.8'

services:
  tomcat:
    image: tomcat:9.0
    ports:
      - "8080:8080"
    volumes:
      # Make sure your WAR file is built and available at this path
      - ./target/my-first-java.war:/usr/local/tomcat/webapps/my-first-java.war
    environment:
      DB_URL: jdbc:mysql://db:3306/mydatabase
      DB_USERNAME: myuser
      DB_PASSWORD: mypassword
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.3
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
