version: '3.8'

services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://db:3306/vamsi
      DB_USERNAME: root
      DB_PASSWORD: Vamsi$97
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.3
    environment:
      MYSQL_DATABASE: vamsi
      MYSQL_USER: root
      MYSQL_PASSWORD: Vamsi$97
      MYSQL_ROOT_PASSWORD: Vamsi$97
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
